#!/usr/bin/env bash
# This script transfers a file from a client to a server using SCP

# Checking  if 4 parameters are passed
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning  parameters to variables
FILE_TO_TRANSFER=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

# Transfering  the file using SCP with strict host key checking disabled
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_TO_TRANSFER" "${USERNAME}@${SERVER_IP}:~/"
